[package]
name = "Pix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["cargo", "color"]}
image = "0.25.1"
rand = "0.9.0-alpha.1"
